language: python
python:
  - "3.6"

before_install:
  - apt-get update
  # install make
  - apt-get install build-essential
  # install virtualenv
  - pip install -U virtualenv

install:
  # disable the default travis install action
  - true

script:
  - make clean
  - make test
